language: php

php:
    - 5.6
    - 7.0
    - 7.1

env:
    global:
        - setup = basic

sudo: false

before_install:
    - composer self-update
    - "wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar && mv selenium-server-standalone-2.53.1.jar ~"
    - "wget http://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip && unzip chromedriver_linux32_23.0.1240.0.zip && mv chromedriver ~"

install:
    - composer install -dev

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # Gives a bit of time for xvfb to start
    - "java -jar ~/selenium-server-standalone-2.53.1.jar -role hub > /dev/null &"
    - sleep 5

script:
    - vendor/bin/behat --config behat.travis.yml --tags '~@javascript' # Skip JS tests for now as we're using the Goutte driver (non-JS)

matrix:
    allow_failures:
        - php: 7.*
    fast_finish: true
