default:
  suites:
    default:
      contexts:
        - FeatureContext
        - CalculatorContext
        - WikipediaContext

  extensions:
    Behat\MinkExtension:
      base_url: 'https://en.wikipedia.org/'
      browser_name: 'firefox'
      default_session: goutte

      # sessions:
      goutte: ~

    Cjm\Behat\StepThroughExtension: ~
